# Κάνοντας compile το <foo>_test.c με μια υλοποίηση <foo>.c του
# συγκεκριμένου τύπου, παράγουμε ένα tets για την υλοποίηση αυτή.

# Υλοποιήσεις μέσω dynamic array: LinkedList
#
LinkedList_test_OBJS = LinkedList_test.o $(MODULES)/LinkedList/LinkedList.o


# Ο βασικός κορμός του Makefile
include ../common.mk