# Λίστα με objects που περιέχει το ER.a library
ER.a_OBJS =						\
	$(MODULES)/LinkedList/LinkedList.o	\
	$(MODULES)/Hash/Hashes.o		\
	$(MODULES)/Hash/Hash.o			\
	$(MODULES)/Utils/ArgUtil.o		\
	$(MODULES)/Utils/FolderUtil.o	\
	$(MODULES)/Utils/TimeUtil.o  \
	$(MODULES)/Item/Item.o			\
	$(MODULES)/Utils/JSONParser.o	\
	$(MODULES)/Utils/CSVParser.o    \
	$(MODULES)/CliqueGroup/CliqueGroup.o \
	$(MODULES)/Utils/StringUtil.o \
	$(MODULES)/TF-IDF/TF-IDF.o \
	$(MODULES)/Tuple/Tuple.o \
	$(MODULES)/LogisticRegression/LogisticRegression.o \
	$(MODULES)/Queue/Queue.o \
	$(MODULES)/JobScheduler/JobScheduler.o \

# Ο βασικός κορμός του Makefile
include ../common.mk