# Λίστα με objects που περιέχει το ER.a library
ER.a_OBJS =						\
	$(MODULES)/LinkedList/LinkedList.o	\
	$(MODULES)/Hash/Hashes.o		\
	$(MODULES)/Hash/Hash.o			\
	$(MODULES)/Utils/ArgUtil.o		\
	$(MODULES)/Utils/FolderUtil.o	\
	$(MODULES)/Utils/Item.o			\
	$(MODULES)/Utils/StringUtil.o

# Ο βασικός κορμός του Makefile
include ../common.mk