name: run-tests
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
    - name: make run
      run: make run CFLAGS=+fPIC
    
    - name: make valgrind
      run: make valgrind CFLAGS-=fPIC
