name: run-tests
on: [push, pull_request]

jobs:
  build-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
    - uses: actions/checkout@v1

    - name: make run-tests
      run: make run-tests CFLAGS=-fPIC

    - name: make run-programs
      run: make run-programs CFLAGS=-fPIC

    - name: make valgrind-tests
      if: matrix.os == 'ubuntu-16.04'
      run: |
        sudo apt install valgrind
        make valgrind-tests CFLAGS=-fPIC

    - name: make valgrind-programs
      if: matrix.os == 'ubuntu-16.04'
      run: |
        sudo apt install valgrind
        make valgrind-programs CFLAGS=-fPIC
        
    - name: Upload
      if: startsWith(github.event.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v2
      with:
        name: compiled-${{ matrix.os }}
        path: .
