name: run-tests
on: [push, pull_request]

jobs:
  build-deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:    
    - uses: actions/checkout@v1
      with: 
        submodules: true

    - name: setup
      run: 
        sudo apt install valgrind;
        wget https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.3.1.tar.gz;
        sudo tar -C /usr/local -xzf libtensorflow-cpu-linux-x86_64-2.3.1.tar.gz;
        sudo ldconfig;
    - name: make run-tests
      run: make run-tests CFLAGS=-fPIC

    - name: make run-programs
      run: make run-programs CFLAGS=-fPIC

    - name: make valgrind-tests
      if: matrix.os == 'ubuntu-20.04'
      run: |
        make valgrind-tests CFLAGS=-fPIC

    - name: make valgrind-programs
      if: matrix.os == 'ubuntu-20.04'
      run: |
        make valgrind-programs CFLAGS=-fPIC
        
    - name: Upload
      if: startsWith(github.event.ref, 'refs/tags/v')
      uses: actions/upload-artifact@v2
      with:
        submodules: true
        name: compiled-${{ matrix.os }}
        path: .
